<?php

// do not edit this file! use the administration panel.

$project = array();
$project['flagtype'] = '2';
$project['needaffix'] = '()';
$project['circumfix'] = '**';
$project['dictDirectEdition'] = 3;
$project['flexionsDepth'] = '1';
$project['restrictedEdit'] = TRUE;
$project['thesAllUsersAllowed'] = TRUE;
$project['thesLockDuration'] = '3600';
$project['thesExtendedSearch'] = FALSE;
$project['thesUpdateByEmail'] = FALSE;

$project['exceptionslist'] = array('--','||');

$prjDic = array();
$prjDic['V'] = 'Classique';
$prjDic['M'] = 'Moderne';
$prjDic['*'] = 'Commun';
$prjDic['R'] = 'Réforme 1990';
$prjDic['A'] = 'Annexe';

$prjDicAbr = array();
$prjDicAbr['V'] = 'Clas.';
$prjDicAbr['M'] = 'Mod.';
$prjDicAbr['*'] = '*';
$prjDicAbr['R'] = 'Réf.';
$prjDicAbr['A'] = 'Anx.';

$activeFields = array();
$activeFields['lemma'] = TRUE;
$activeFields['flags'] = TRUE;
$activeFields['lex'] = TRUE;
$activeFields['sem'] = TRUE;
$activeFields['ety'] = TRUE;
$activeFields['dic'] = TRUE;
$activeFields['ifq'] = TRUE;
$activeFields['po'] = TRUE;
$activeFields['is'] = TRUE;
$activeFields['ds'] = FALSE;
$activeFields['ts'] = FALSE;
$activeFields['ip'] = FALSE;
$activeFields['dp'] = FALSE;
$activeFields['tp'] = FALSE;
$activeFields['sp'] = FALSE;
$activeFields['pa'] = FALSE;
$activeFields['st'] = TRUE;
$activeFields['al'] = FALSE;
$activeFields['ph'] = FALSE;

$prjCustomlinks = array();
$prjCustomlinks['Dicollecte'] = 'http://www.dicollecte.org/dictionary.php?prj=fr&amp;lemma=%s';
$prjCustomlinks['TLFi'] = 'http://www.cnrtl.fr/definition/%s';
$prjCustomlinks['Académie'] = 'http://www.cnrtl.fr/definition/academie9/%s';
$prjCustomlinks['Wiktionnaire'] = 'http://fr.wiktionary.org/wiki/%s';
$prjCustomlinks['Littré'] = 'http://littre.reverso.net/dictionnaire-francais/definition/%s';
$prjCustomlinks['GDT'] = 'http://liendex.ptaff.ca/v2/fr_CA/francais/grand_dictionnaire_terminologique/%s';
$prjCustomlinks['Reverso'] = 'http://dictionnaire.reverso.net/francais-definition/%s';
$prjCustomlinks['Larousse'] = 'http://www.google.fr/search?q=%22%s%22+site:larousse.fr&amp;lr=lang_fr&amp;filter=0';
$prjCustomlinks['Prénoms'] = 'http://meilleursprenoms.com/stats/histogram.php3?recherche=%s&amp;image.x=0&amp;image.y=0';
$prjCustomlinks['Google'] = 'http://www.google.fr/search?q=%22%s%22&amp;lr=lang_fr&amp;safe=off&amp;filter=0';
$prjCustomlinks['Livres'] = 'http://www.google.fr/search?q=%22%s%22&amp;hl=fr&amp;safe=off&amp;tbs=bks:1,lr:lang_1fr';
$prjCustomlinks['Wikipédia'] = 'http://www.google.fr/search?q=%22%s%22+site:fr.wikipedia.org&amp;lr=lang_fr&amp;filter=0';
$prjCustomlinks['Bing'] = 'http://www.bing.com/search?q=%s&amp;go=&amp;form=QBLH&amp;filt=lf';

?>