// JavaScript Document
var flagsValues = [['Nom/adjectif simple ou épicène',''],['Pluriel en s','S.()'],['Pluriel en s, élisions','S*()'],['Pluriel en x','X.()'],['Pluriel en x, élisions','X*()'],['Nom/adjectif non épicène',''],['Pluriel en s','F.()'],['Pluriel en s, élisions','F*()'],['Pluriel en x','W.()'],['Pluriel en x, élisions','W*()'],['Divers',''],['Élisions pour mot invariable','L\'D\'Q\''],['Pluriel des mots anglais','A.()'],['Pluriel des mots anglais, élisions','A*()'],['Pluriel des mots latins/italiens','I.()'],['Pluriel des mots latins/italiens, élisions','I*()'],['Élisions',''],['Adverbe','D\'Q\''],['Prénom, Ville','L\'D\'Q\''],['Pays','L\'D\''],['Région','L\''],['Verbe du 1er groupe (exemples)',''],['Pas d’élisions, part. passé variable','a0p+()'],['Pas d’élisions, part. passé invariable','a0p.()'],['Intransitif (élisions)','a1p.()'],['Transitif (élisions)','a2p+()'],['Pronominal (élisions)','a3p+()'],['Transitif et pronominal (élisions)','a4p+()'],['Transitif indirect (élisions)','a5p.()'],['Verbes du 2e groupe (exemples)',''],['Pas d’élisions, part. passé variable','f0p+()'],['Pas d’élisions, part. passé invariable','f0p.()'],['Intransitif (élisions)','f1p.()'],['Transitif (élisions)','f2p+()'],['Pronominal (élisions)','f3p+()'],['Transitif et pronominal (élisions)','f4p+()'],['Transitif indirect (élisions)','f5p.()']];
var poValues = [['Substantif',''],['Nom','nom'],['Adjectif','adj'],['Nom et adjectif','nom adj'],['Verbe',''],['Verbe du premier groupe','v1'],['Verbe du deuxième groupe','v2'],['Complément',''],['Adverbe','adv'],['Locution adverbiale','loc.adv'],['Locution adjectivale','loc.adj'],['Nom propre',''],['Prénom','prn'],['Patronyme','patr'],['Ville, pays, montagne, île, fleuve, mer, etc.','geo'],['Autres',''],['Interjection','interj'],['Mot grammatical','mg'],['Déterminant','det'],['Préposition','prep'],['Nombre','nb'],['Conjonction','cj'],['Pronom','pro']];
var isValues = [['Épicène',''],['Épicène','epi'],['Épicène singulier','epi sg'],['Épicène pluriel','epi pl'],['Épicène invariable','epi inv'],['Masculin',''],['Masculin','mas'],['Masculin singulier','mas sg'],['Masculin pluriel','mas pl'],['Masculin invariable','mas inv'],['Féminin',''],['Féminin','fem'],['Féminin singulier','fem sg'],['Féminin pluriel','fem pl'],['Féminin invariable','fem inv']];
var dsValues = [];
var tsValues = [];
var ipValues = [];
var dpValues = [];
var tpValues = [];
var spValues = [];
var paValues = [];
var lexValues = [['Variantes orthographiques',''],['Variante orthographique proche','var'],['Graphie alternative éloignée','alt'],['répertoriée par un dictionnaire de référence','dic'],['Usage',''],['Rare (< 2000 occur. sur Google fr)','rare'],['Vieux, désuet, inusité','vieux'],['Néologisme','néo'],['Familier','fam'],['Péjoratif','péj'],['Faux-ami','fxa'],['Catégorie',''],['Symbole','symb'],['Abréviation','abr'],['Abréviation typographique','abty'],['Ville, village, quartier','cité'],['Coloris','col'],['Nom déposé','dép'],['Produit, compagnie','TM'],['Figure historique','hist'],['Onomatopée','onom'],['Variétés nationales/régionales',''],['Africanisme','afr'],['Belgicisme','belg'],['Francisme','fra'],['Helvétisme','helv'],['Québécisme','québ'],['Régionalisme','rég'],['Langues régionales',''],['Occitan, provençal, auvergnat, gascon, etc.','occ'],['Langue d’oïl, normand, champenois, lorrain, wallon, etc.','oil'],['Celte, gaulois, gaélique, brittonique, breton, etc.','celt'],['Origine étrangère',''],['Latin','lat'],['Grec','grec'],['Anglais','angl'],['Allemand','all'],['Néerlandais','néer'],['Flamand','fla'],['Italien','ita'],['Espagnol','esp'],['Portugais','port'],['Danois','dan'],['Norvégien','norv'],['Suédois','sué'],['Finnois','finn'],['Islandais','isl'],['Russe','rus'],['Ukrainien','ukr'],['Polonais','pol'],['Turc','turc'],['Persan','pers'],['Arabe','ara'],['Hébreu','héb'],['Hindi','hind'],['Sanskrit','sskr'],['Chinois','chin'],['Japonais','jap'],['Américain (natifs)','amér'],['Autre origine étrangère','étr']];
var semValues = [['Nature',''],['Botanique','bot'],['Minéralogie','minér'],['Mycologie','myco'],['Zoologie','zool'],['Divers',''],['Langue','lang'],['Histoire','hist'],['Sciences',''],['Astronomie','astron'],['Biologie','bio'],['Biochimie','bioch'],['Chimie','chim'],['Cristallographie','cristal'],['Géographie','géogr'],['Géologie','géol'],['Logique','log'],['Mathématiques','math'],['Paléontologie','paléo'],['Physique','phys'],['Sciences','sc'],['Médecine',''],['Anatomie','anat'],['Bactériologie','bact'],['Chirurgie','chir'],['Médecine','méd'],['Neurologie','neuro'],['Pathologie','patho'],['Pharmaceutique','pharma'],['Physiologie','physio'],['Pensée',''],['Anthropologie','anthr'],['Démographie','démogr'],['Écologie','écolo'],['Économie','écono'],['Ethnologie','éthno'],['Éthologie','étho'],['Épistémologie','épis'],['Linguistique','lingu'],['Philosophie','philo'],['Phonétique','phonét'],['Psychologie','psycho'],['Psychanalyse','psychan'],['Psychiatrie','psychia'],['Sociologie','socio'],['Mysticisme',''],['Alchimie','alch'],['Astrologie','astrol'],['Christianisme','chris'],['Ésotérisme','éso'],['Islam','islam'],['Judaïsme','jud'],['Mythologie','myth'],['Religion','reli'],['Techniques',''],['Aéronautique','aéron'],['Astronautique','astronaut'],['Armurerie','arm'],['Didactique','didac'],['Électronique','électro'],['Haute technologie (Hi-tech)','hitech'],['Imprimerie','impr'],['Informatique','info'],['Ingénierie','ingé'],['Logistique','logis'],['Mécanique','méca'],['Métallurgie','métal'],['Technique','techni'],['Blabla',''],['Administration','admin'],['Communication','comm'],['Commerce','march'],['Droit','droit'],['Politique','polit'],['Publicité','pub'],['Métiers',''],['Agriculture','agri'],['Arboriculture','arbo'],['Architecture','archi'],['Bâtiment','bât'],['Charpenterie','charp'],['Construction','constr'],['Ébénisterie','ébén'],['Maçonnerie','maçon'],['Marine','marin'],['Militaire','milit'],['Pêche','pêche'],['Sylviculture','sylvi'],['Urbanisme','urba'],['Argent',''],['Comptabilité','compta'],['Finances','fin'],['Fiscalité','fisc'],['Arts',''],['Arts','art'],['Calligraphie','calli'],['Chant','chant'],['Cinéma','ciné'],['Danse','danse'],['Littérature','litt'],['Musique','mus'],['Peinture','peint'],['Photographie','photo'],['Poésie','poés'],['Sculpture','sculp'],['Théâtre','théâ'],['Passe-temps',''],['Alcool','alcool'],['Chasse','chass'],['Cuisine','cuis'],['Héraldique','hérald'],['Jardinage','jard'],['Jeux','jeu'],['Numismatique','numis'],['Sport','sport'],];
