// JavaScript Document
var flagsValues = [['subcategoryA',''],['description 1','elem1'],['description 2','elem2'],['subcategoryB',''],['description 3','elem3'],['description 4','elem4'],['description 5','elem5'],['subcategoryC',''],['description 6','elem6'],['subcategoryD',''],['description 7','elem7'],['description 8','elem8'],['description 9','elem9'],['description 10','elem10'],['description 11','elem11'],['description 12','elem12'],['description 13','elem13']];
var poValues = [['Noun','noun'],['Adjective','adj'],['Verb',''],['Regular verb','r.verb'],['Irregular verb','i.verb'],['Miscellaneous',''],['Adverb','adv'],['Interjection','interj'],['Onomatopeoa','onom'],['Grammatical word',''],['Pronoun','pron'],['Preposition','prep'],['Conjonction','conj'],['Article','art'],['Proper name',''],['First Name','fn'],['Name','name'],['Patronym','patr']];
var isValues = [['Singular','sg'],['Plural','pl'],['Invariable','inv'],['Masculine','mas'],['Feminine','fem']];
var dsValues = [['subcategoryA',''],['description 1','elem1'],['description 2','elem2'],['subcategoryB',''],['description 3','elem3'],['description 4','elem4'],['description 5','elem5'],['subcategoryC',''],['description 6','elem6'],['subcategoryD',''],['description 7','elem7'],['description 8','elem8'],['description 9','elem9'],['description 10','elem10'],['description 11','elem11'],['description 12','elem12'],['description 13','elem13']];
var tsValues = [['subcategoryA',''],['description 1','elem1'],['description 2','elem2'],['subcategoryB',''],['description 3','elem3'],['description 4','elem4'],['description 5','elem5'],['subcategoryC',''],['description 6','elem6'],['subcategoryD',''],['description 7','elem7'],['description 8','elem8'],['description 9','elem9'],['description 10','elem10'],['description 11','elem11'],['description 12','elem12'],['description 13','elem13']];
var ipValues = [['subcategoryA',''],['description 1','elem1'],['description 2','elem2'],['subcategoryB',''],['description 3','elem3'],['description 4','elem4'],['description 5','elem5'],['subcategoryC',''],['description 6','elem6'],['subcategoryD',''],['description 7','elem7'],['description 8','elem8'],['description 9','elem9'],['description 10','elem10'],['description 11','elem11'],['description 12','elem12'],['description 13','elem13']];
var dpValues = [['subcategoryA',''],['description 1','elem1'],['description 2','elem2'],['subcategoryB',''],['description 3','elem3'],['description 4','elem4'],['description 5','elem5'],['subcategoryC',''],['description 6','elem6'],['subcategoryD',''],['description 7','elem7'],['description 8','elem8'],['description 9','elem9'],['description 10','elem10'],['description 11','elem11'],['description 12','elem12'],['description 13','elem13']];
var tpValues = [['subcategoryA',''],['description 1','elem1'],['description 2','elem2'],['subcategoryB',''],['description 3','elem3'],['description 4','elem4'],['description 5','elem5'],['subcategoryC',''],['description 6','elem6'],['subcategoryD',''],['description 7','elem7'],['description 8','elem8'],['description 9','elem9'],['description 10','elem10'],['description 11','elem11'],['description 12','elem12'],['description 13','elem13']];
var spValues = [['subcategoryA',''],['description 1','elem1'],['description 2','elem2'],['subcategoryB',''],['description 3','elem3'],['description 4','elem4'],['description 5','elem5'],['subcategoryC',''],['description 6','elem6'],['subcategoryD',''],['description 7','elem7'],['description 8','elem8'],['description 9','elem9'],['description 10','elem10'],['description 11','elem11'],['description 12','elem12'],['description 13','elem13']];
var paValues = [['subcategoryA',''],['description 1','elem1'],['description 2','elem2'],['subcategoryB',''],['description 3','elem3'],['description 4','elem4'],['description 5','elem5'],['subcategoryC',''],['description 6','elem6'],['subcategoryD',''],['description 7','elem7'],['description 8','elem8'],['description 9','elem9'],['description 10','elem10'],['description 11','elem11'],['description 12','elem12'],['description 13','elem13']];
var grammValues = [];
var lexValues = [['Usage',''],['Rare','rare'],['Old, obsolete','old'],['Neologism','neo'],['Categories',''],['Abbreviation','abr'],['Alternative spelling','alt'],['Symbol','symb'],['Product','TM'],['Loanwords',''],['French','fr'],['German','ge'],['Greek','gr'],['Latin','lat'],];
